---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: validators-operator
    prometheus: "true"
  name: validator-operator-metrics
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "operator-chart.fullname" . }}-0

