apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "operator-chart.fullname" . }}
  labels:
    {{- include "operator-chart.labels" . | nindent 4 }}
spec:
  serviceName: validators-operator-service
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "operator-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        debug: "true"
        {{- range .Values.pod_annotation }}
        {{.name}}: {{.value | quote}}
        {{- end }}
      labels:
        {{- include "operator-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator-chart.serviceAccountName" . }}
#      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          command:
            {{- toYaml .Values.command | nindent 12 }}        
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
